### ISSUE TITLE
Not able to do web-ext run or web-ext build

### ISSUE THREAD

**Issue by craigjaneway** [dirkjanm/firefox-send-to-xbmc#65]
This what I get when I do web-ext run...

C:\Users\craig\Downloads\firefox-send-to-xbmc-master\firefox-send-to-xbmc-master>web-ext run

TypeError: Cannot read property 'R_OK' of undefined
    at fileIsReadable (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\src\util\file-exists.js:24:42)
    at _callee$ (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\src\util\file-exists.js:28:11)
    at tryCatch (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:1
    at new Promise (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\core-js\library\modules\es6.promise.js:177:1)
    at C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:1
    at fileExists (C:\Users\craig\AppData\Roaming\npm\node_modules\web-ext\dist\web-ext.js:13015:17)

**Comment by dirkjanm** [comment]
Been a while since I tried this, but can you try running this from the `webextension` folder instead of the root?

**Comment by craigjaneway** [comment]
Opened command window from webextension folder and same result.

**Comment by dirkjanm** [comment]
I just updated to the latest web-ext version here (2.7.0) and it runs fine as long as it is ran from the webextension directory. I'm pretty sure this issue is not related to the extension but more to your local setup (combination of dependencies or node.js version?). If you do find anything which points at the extension being at fault here feel free to reopen the issue.
